### ISSUE TITLE
Запретить возможность редактирование системных файлов ОС

### ISSUE THREAD

**Issue by xdirex** [maindefine/ruxe-engine#95]
Пример (linux): 
rpanel/index.php?action=edit&file=/etc/hosts

**Comment by maindefine** [comment]
Проблема не в RE, а в настройках сервера. http://den.bz/article/ogranichivaem-katalog-v-kotoryjj-mozhno-poluchit-dostup-s-pomoshhyu-php.html

**Comment by maindefine** [comment]
file_exists(): open_basedir restriction in effect. File(/etc/hosts) is not within the allowed path(s): (/var/www/ruxe-engine.ru/web/)	/var/www/ruxe-engine.ru/web/rpanel/index.php ;)

**Comment by xdirex** [comment]
Безопасность CMS зависит от того где она установлена? ;-)

**Comment by maindefine** [comment]
На любом шаред хостинге доступ будет закрыт. На собственном сервере безопасность ВНЕЗАПНО зависит от администратора сервера.
